import React from 'react';
import { 
  PieChart, Pie, Cell, ResponsiveContainer, Tooltip as RechartsTooltip, Legend,
  Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis 
} from 'recharts';
import { AnalysisResult } from '../types';
import InfoTooltip from './InfoTooltip';

interface AnalysisChartProps {
  result: AnalysisResult;
}

const AnalysisChart: React.FC<AnalysisChartProps> = ({ result }) => {
  // Data for Pie Chart
  const pieData = [
    { name: 'AI Probability', value: result.probabilityAI },
    { name: 'Human Probability', value: 100 - result.probabilityAI },
  ];

  // Determine colors based on result
  const isLikelyAI = result.probabilityAI > 50;
  const aiColor = isLikelyAI ? '#ef4444' : '#94a3b8'; // Red if high, slate if low
  const humanColor = !isLikelyAI ? '#22c55e' : '#94a3b8'; // Green if high, slate if low

  const PIE_COLORS = [aiColor, humanColor];

  // Data for Radar Chart (Features)
  const radarData = result.keyFeatures && result.keyFeatures.length > 0 
    ? result.keyFeatures.map(kf => ({
        subject: kf.feature.length > 12 ? kf.feature.substring(0, 12) + '..' : kf.feature,
        fullFeature: kf.feature,
        A: kf.impactScore,
        fullMark: 100
      }))
    : [{ subject: 'No Data', A: 0, fullMark: 100 }];

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
      
      {/* Probability Gauge (Pie Chart) */}
      <div className="h-72 md:h-80 bg-white dark:bg-slate-900 border border-slate-300 dark:border-slate-800 rounded-2xl p-4 flex flex-col shadow-lg shadow-slate-200/40 dark:shadow-none relative overflow-hidden group hover:border-slate-400 dark:hover:border-slate-700 transition-all">
        {/* Header */}
        <div className="flex items-center justify-center mb-1 shrink-0 z-10 relative">
          <h3 className="text-slate-700 dark:text-slate-300 font-semibold text-xs uppercase tracking-widest">AI Probability</h3>
          <InfoTooltip content="The estimated likelihood (0-100%) that the analyzed content was generated by Artificial Intelligence algorithms." />
        </div>
        
        {/* Chart Container */}
        <div className="flex-1 min-h-0 w-full relative">
            <ResponsiveContainer width="100%" height="100%">
            <PieChart margin={{ top: 0, right: 0, left: 0, bottom: 0 }}>
                <Pie
                data={pieData}
                cx="50%"
                cy="45%" // Moved up slightly to make room for legend at bottom
                innerRadius="55%"
                outerRadius="75%"
                fill="#8884d8"
                paddingAngle={5}
                dataKey="value"
                stroke="none"
                startAngle={90}
                endAngle={-270}
                cornerRadius={6}
                >
                {pieData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={PIE_COLORS[index % PIE_COLORS.length]} />
                ))}
                </Pie>
                <RechartsTooltip 
                contentStyle={{ backgroundColor: 'var(--tooltip-bg, #0f172a)', borderColor: 'var(--tooltip-border, #334155)', color: 'var(--tooltip-text, #f8fafc)', borderRadius: '12px', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.5)' }}
                itemStyle={{ color: 'var(--tooltip-text, #f8fafc)', fontWeight: 500 }}
                formatter={(value) => [`${value}%`]}
                />
                <Legend 
                    verticalAlign="bottom" 
                    height={36} 
                    iconType="circle" 
                    iconSize={8}
                    wrapperStyle={{ color: '#64748b', fontSize: '11px', paddingTop: '10px', bottom: 0 }} 
                />
            </PieChart>
            </ResponsiveContainer>

            {/* Centered Percentage Text - positioned at 38% top to match Pie cy */}
            <div className="absolute top-[38%] left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-center pointer-events-none">
                <span className={`text-3xl font-bold tracking-tight ${isLikelyAI ? 'text-red-500 dark:text-red-400' : 'text-green-600 dark:text-green-400'}`}>
                    {result.probabilityAI}%
                </span>
            </div>
        </div>
      </div>

      {/* Feature Impact Radar */}
      <div className="h-72 md:h-80 bg-white dark:bg-slate-900 border border-slate-300 dark:border-slate-800 rounded-2xl p-4 flex flex-col shadow-lg shadow-slate-200/40 dark:shadow-none relative overflow-hidden group hover:border-slate-400 dark:hover:border-slate-700 transition-all">
        <div className="flex items-center justify-center mb-1 shrink-0 z-10 relative">
          <h3 className="text-slate-700 dark:text-slate-300 font-semibold text-xs uppercase tracking-widest">Feature Impact</h3>
          <InfoTooltip content="Visualizes specific artifacts found in the content. Points further from the center indicate features that strongly suggest AI generation." />
        </div>

        <div className="flex-1 min-h-0 w-full relative">
            <ResponsiveContainer width="100%" height="100%">
            <RadarChart cx="50%" cy="50%" outerRadius="65%" data={radarData}>
                <PolarGrid stroke="#94a3b8" strokeOpacity={0.2} />
                <PolarAngleAxis 
                dataKey="subject" 
                tick={{ fill: '#64748b', fontSize: 10, fontWeight: 500 }} 
                />
                <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                <Radar
                name="Impact Score"
                dataKey="A"
                stroke="#6366f1"
                strokeWidth={2}
                fill="#6366f1"
                fillOpacity={0.4}
                />
                <RechartsTooltip 
                contentStyle={{ backgroundColor: 'var(--tooltip-bg, #0f172a)', borderColor: 'var(--tooltip-border, #334155)', color: 'var(--tooltip-text, #f8fafc)', borderRadius: '12px', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.5)' }}
                itemStyle={{ color: '#818cf8', fontWeight: 500 }}
                formatter={(value: number) => [`${value}%`, 'Impact']}
                labelStyle={{ color: '#cbd5e1' }}
                />
            </RadarChart>
            </ResponsiveContainer>
        </div>
      </div>
      
      {/* CSS Vars for Recharts Tooltip Theme Adaptation */}
      <style>{`
        :root {
          --tooltip-bg: #ffffff;
          --tooltip-border: #cbd5e1;
          --tooltip-text: #1e293b;
        }
        .dark {
          --tooltip-bg: #0f172a;
          --tooltip-border: #334155;
          --tooltip-text: #f8fafc;
        }
      `}</style>
    </div>
  );
};

export default AnalysisChart;